-- MySQL Script generated by MySQL Workbench
-- mié 03 nov 2021 23:26:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pedidos-pizzeria-web
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pedidos-pizzeria-web` ;

-- -----------------------------------------------------
-- Schema pedidos-pizzeria-web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pedidos-pizzeria-web` ;
USE `pedidos-pizzeria-web` ;

-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`roles` (
  `IdRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`formulario` (
  `IdFormulario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `alias` VARCHAR(45) NULL,
  `idSistema` INT NOT NULL,
  PRIMARY KEY (`IdFormulario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`acceso` (
  `IdAcceso` INT NOT NULL AUTO_INCREMENT,
  `acceso` TINYINT NOT NULL DEFAULT 0,
  `IdFormulario` INT NOT NULL,
  `IdRol` INT NOT NULL,
  PRIMARY KEY (`IdAcceso`),
  INDEX `Acceso_ibfk_2` (`IdRol` ASC),
  INDEX `fk_acceso_1_idx` (`IdFormulario` ASC),
  CONSTRAINT `Acceso_ibfk_2`
    FOREIGN KEY (`IdRol`)
    REFERENCES `pedidos-pizzeria-web`.`roles` (`IdRol`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_acceso_1`
    FOREIGN KEY (`IdFormulario`)
    REFERENCES `pedidos-pizzeria-web`.`formulario` (`IdFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`tipoPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`tipoPersona` (
  `IdTipoPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdTipoPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`tipoDocumentoIdentidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`tipoDocumentoIdentidad` (
  `IdTipoDocIdentidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `cantidad_caracteres` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IdTipoDocIdentidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`documentoIdentidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`documentoIdentidad` (
  `IdDocumentoIdentidad` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `IdTipoDocIdentidad` INT NOT NULL,
  PRIMARY KEY (`IdDocumentoIdentidad`),
  INDEX `R_29` (`IdTipoDocIdentidad` ASC),
  CONSTRAINT `DocumentoIdentidad_ibfk_1`
    FOREIGN KEY (`IdTipoDocIdentidad`)
    REFERENCES `pedidos-pizzeria-web`.`tipoDocumentoIdentidad` (`IdTipoDocIdentidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`tipoestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`tipoestado` (
  `IdTipoEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdTipoEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`estado` (
  `IdEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `IdTipoEstado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IdEstado`),
  INDEX `fk_Estado_1_idx` (`IdTipoEstado` ASC),
  CONSTRAINT `fk_Estado_1`
    FOREIGN KEY (`IdTipoEstado`)
    REFERENCES `pedidos-pizzeria-web`.`tipoestado` (`IdTipoEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`persona` (
  `IdPersona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(150) NULL DEFAULT NULL,
  `apellidos` VARCHAR(150) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NULL,
  `IdTipoPersona` INT NOT NULL,
  `IdDocumentoIdentidad` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  PRIMARY KEY (`IdPersona`),
  INDEX `R_18` (`IdTipoPersona` ASC),
  INDEX `R_30` (`IdDocumentoIdentidad` ASC),
  INDEX `R_36` (`IdEstado` ASC),
  CONSTRAINT `Persona_ibfk_1`
    FOREIGN KEY (`IdTipoPersona`)
    REFERENCES `pedidos-pizzeria-web`.`tipoPersona` (`IdTipoPersona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Persona_ibfk_2`
    FOREIGN KEY (`IdDocumentoIdentidad`)
    REFERENCES `pedidos-pizzeria-web`.`documentoIdentidad` (`IdDocumentoIdentidad`),
  CONSTRAINT `Persona_ibfk_3`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `IdPersona` INT NOT NULL,
  `nombre_usuario` VARCHAR(50) NULL,
  `contrasenha` VARCHAR(50) NULL,
  PRIMARY KEY (`IdCliente`),
  INDEX `R_43` (`IdPersona` ASC),
  CONSTRAINT `Cliente_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `pedidos-pizzeria-web`.`persona` (`IdPersona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`tipocomprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`tipocomprobante` (
  `IdTipoComprobante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `IdEstado` INT NOT NULL,
  PRIMARY KEY (`IdTipoComprobante`),
  INDEX `R_39` (`IdEstado` ASC),
  CONSTRAINT `TipoComprobante_ibfk_1`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`distrito` (
  `IdDistrito` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cobertura` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdDistrito`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`direccionCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`direccionCliente` (
  `iddireccionCliente` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(250) NULL,
  `referencia` VARCHAR(250) NULL,
  `latitud` DECIMAL(18,6) NULL,
  `longitud` DECIMAL(18,6) NULL,
  `principal` TINYINT NULL,
  `idDistrito` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`iddireccionCliente`),
  INDEX `fk_direccionCliente_1_idx` (`idDistrito` ASC),
  INDEX `fk_direccionCliente_2_idx` (`idCliente` ASC),
  CONSTRAINT `fk_direccionCliente_1`
    FOREIGN KEY (`idDistrito`)
    REFERENCES `pedidos-pizzeria-web`.`distrito` (`IdDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccionCliente_2`
    FOREIGN KEY (`idCliente`)
    REFERENCES `pedidos-pizzeria-web`.`cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`pedido` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL,
  `observaciones` VARCHAR(50) NULL DEFAULT NULL,
  `IdCliente` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  `fecha_preparacion` DATETIME NULL,
  `fecha_entrega` DATETIME NULL,
  `idDireccionEnvio` INT NOT NULL,
  PRIMARY KEY (`IdPedido`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `R_15` (`IdEstado` ASC),
  INDEX `R_26` (`IdCliente` ASC),
  INDEX `fk_pedido_1_idx` (`idDireccionEnvio` ASC),
  CONSTRAINT `Pedido_ibfk_1`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Pedido_ibfk_2`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `pedidos-pizzeria-web`.`cliente` (`IdCliente`),
  CONSTRAINT `fk_pedido_1`
    FOREIGN KEY (`idDireccionEnvio`)
    REFERENCES `pedidos-pizzeria-web`.`direccionCliente` (`iddireccionCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`comprobante` (
  `IdComprobante` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL DEFAULT '0',
  `fecha_emision` DATETIME NOT NULL,
  `subtotal` DECIMAL(18,2) NOT NULL,
  `IdPedido` INT NOT NULL,
  `IdTipoComprobante` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  `total` DECIMAL(18,2) NULL,
  PRIMARY KEY (`IdComprobante`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `R_14` (`IdTipoComprobante` ASC),
  INDEX `R_25` (`IdPedido` ASC),
  INDEX `R_45` (`IdEstado` ASC),
  CONSTRAINT `Comprobante_ibfk_1`
    FOREIGN KEY (`IdTipoComprobante`)
    REFERENCES `pedidos-pizzeria-web`.`tipocomprobante` (`IdTipoComprobante`),
  CONSTRAINT `Comprobante_ibfk_2`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `pedidos-pizzeria-web`.`pedido` (`IdPedido`),
  CONSTRAINT `Comprobante_ibfk_3`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`repartidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`repartidor` (
  `idRepartidor` INT NOT NULL AUTO_INCREMENT,
  `IdPersona` INT NOT NULL,
  `placa_unidad` VARCHAR(10) NULL,
  PRIMARY KEY (`idRepartidor`),
  UNIQUE INDEX `idRepartidor_UNIQUE` (`idRepartidor` ASC),
  INDEX `fk_repartidor_1_idx` (`IdPersona` ASC),
  CONSTRAINT `fk_repartidor_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `pedidos-pizzeria-web`.`persona` (`IdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`envio` (
  `IdEnvio` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` DATETIME NOT NULL,
  `hora_fin` DATETIME NOT NULL,
  `numero` INT NOT NULL DEFAULT '0',
  `idRepartidor` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  PRIMARY KEY (`IdEnvio`),
  INDEX `R_35` (`IdEstado` ASC),
  INDEX `fk_envio_1_idx` (`idRepartidor` ASC),
  CONSTRAINT `Envio_ibfk_2`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_envio_1`
    FOREIGN KEY (`idRepartidor`)
    REFERENCES `pedidos-pizzeria-web`.`repartidor` (`idRepartidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`detalleEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`detalleEnvio` (
  `IdDetalleEnvio` INT NOT NULL AUTO_INCREMENT,
  `hora_entrega` DATETIME NOT NULL,
  `observaciones` VARCHAR(500) NULL DEFAULT NULL,
  `IdEnvio` INT NOT NULL,
  `IdPedido` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  PRIMARY KEY (`IdDetalleEnvio`),
  INDEX `fk_detalleEnvio_1_idx` (`IdEstado` ASC),
  INDEX `fk_detalleEnvio_2_idx` (`IdEnvio` ASC),
  INDEX `fk_detalleEnvio_3_idx` (`IdPedido` ASC),
  CONSTRAINT `fk_detalleEnvio_1`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleEnvio_2`
    FOREIGN KEY (`IdEnvio`)
    REFERENCES `pedidos-pizzeria-web`.`envio` (`IdEnvio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleEnvio_3`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `pedidos-pizzeria-web`.`pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`tipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`tipoProducto` (
  `idTipoProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `descripcion` VARCHAR(500) NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  `imagen` VARCHAR(500) NULL,
  `idTipoProducto` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_producto_1_idx` (`IdEstado` ASC),
  INDEX `fk_producto_2_idx` (`idTipoProducto` ASC),
  CONSTRAINT `fk_producto_1`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_2`
    FOREIGN KEY (`idTipoProducto`)
    REFERENCES `pedidos-pizzeria-web`.`tipoProducto` (`idTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`detallepedido` (
  `IdDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `IdPedido` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `precio` DECIMAL(18,2) NULL,
  PRIMARY KEY (`IdDetallePedido`),
  INDEX `R_11` (`IdPedido` ASC),
  INDEX `fk_detallepedido_1_idx` (`idProducto` ASC),
  CONSTRAINT `DetallePedido_ibfk_1`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `pedidos-pizzeria-web`.`pedido` (`IdPedido`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_detallepedido_1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `pedidos-pizzeria-web`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`tipopizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`tipopizza` (
  `IdTipoPizza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`IdTipoPizza`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`tamanho` (
  `IdTamanho` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `cantidadPorciones` INT NOT NULL,
  PRIMARY KEY (`IdTamanho`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`pizza` (
  `IdPizza` INT NOT NULL AUTO_INCREMENT,
  `IdTipoPizza` INT NOT NULL,
  `IdTamanho` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`IdPizza`),
  INDEX `R_12` (`IdTipoPizza` ASC),
  INDEX `R_44` (`IdEstado` ASC),
  INDEX `Pizza_ibfk_2` (`IdTamanho` ASC),
  INDEX `fk_pizza_1_idx` (`idProducto` ASC),
  CONSTRAINT `Pizza_ibfk_1`
    FOREIGN KEY (`IdTipoPizza`)
    REFERENCES `pedidos-pizzeria-web`.`tipopizza` (`IdTipoPizza`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Pizza_ibfk_2`
    FOREIGN KEY (`IdTamanho`)
    REFERENCES `pedidos-pizzeria-web`.`tamanho` (`IdTamanho`),
  CONSTRAINT `Pizza_ibfk_3`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `pedidos-pizzeria-web`.`estado` (`IdEstado`),
  CONSTRAINT `fk_pizza_1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `pedidos-pizzeria-web`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `pedidos-pizzeria-web`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos-pizzeria-web`.`usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `contrasenha` VARCHAR(50) NOT NULL,
  `IdPersona` INT NOT NULL,
  `IdRol` INT NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `R_32` (`IdPersona` ASC),
  INDEX `R_34` (`IdRol` ASC),
  CONSTRAINT `Usuario_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `pedidos-pizzeria-web`.`persona` (`IdPersona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Usuario_ibfk_2`
    FOREIGN KEY (`IdRol`)
    REFERENCES `pedidos-pizzeria-web`.`roles` (`IdRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;

USE `pedidos-pizzeria-web` ;
